services:
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile.prod
    ports:
      - 3000
    volumes:
      - ./client/:/client
      - /client/node_modules

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - client
